### ISSUE TITLE
lect-player-web 1.0.0 build error: HTTP error 404 for a GitHub resource

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#244]
**Describe the bug**
On the latest version of lectureStudio (Git commit https://github.com/lectureStudio/lectureStudio/commit/23ca30ceccb4ebdbd2238dfe644d9e55c8c68b92), I'm unable to build the project because of an HTTP 404 error for a node-sass resource hosted on GitHub. (I will attach the logs!)

As far as I can see, the requested URL (https://github.com/sass/node-sass/releases/download/v5.0.0/linux-x64-79_binding.node) is indeed dead. 

**To Reproduce**
1. Clone this repository.
2. Run `mvn install -DskipTests`

**Expected behavior**
The build process should succeed.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 20.04 (in a container)

**Additional context**

lectureStudio currently uses NodeJS v13.14.0 - is it possible that this is not supported anymore by SASS v5.0.0?

Maybe, these links are helpful:
* https://github.com/sass/node-sass/issues/3148
* https://github.com/sass/node-sass#node-version-support-policy
* https://github.com/nodejs/Release#release-schedule

Log output:
```
[INFO] --------------< org.lecturestudio.player:lect-player-web >--------------
[INFO] Building lect-player-web 1.0.0                                   [20/24]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-license) @ lect-player-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-jgit-buildnumber-plugin:1.2.10:extract-buildnumber (git-buildnumber) @ lect-player-web ---
[INFO] 
[INFO] --- frontend-maven-plugin:1.11.2:install-node-and-npm (install node and npm) @ lect-player-web ---
[INFO] Installing node version v13.14.0
[INFO] Unpacking /root/.m2/repository/com/github/eirslett/node/13.14.0/node-13.14.0-linux-x64.tar.gz into /data/lect-player-web/target/node/tmp
[INFO] Copying node binary from /data/lect-player-web/target/node/tmp/node-v13.14.0-linux-x64/bin/node to /data/lect-player-web/target/node/node
[INFO] Extracting NPM
[INFO] Installed node locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.11.2:npm (npm install) @ lect-player-web ---
[INFO] Running 'npm install' in /data/lect-player-web/src/main/frontend
[INFO] 
[INFO] > node-sass@5.0.0 install /data/lect-player-web/src/main/frontend/node_modules/node-sass
[INFO] > node scripts/install.js
[INFO] 
[INFO] Downloading binary from https://github.com/sass/node-sass/releases/download/v5.0.0/linux-x64-79_binding.node
[INFO] Cannot download "https://github.com/sass/node-sass/releases/download/v5.0.0/linux-x64-79_binding.node": 
[INFO] 
[INFO] HTTP error 404 Not Found
[INFO] 
[INFO] Hint: If github.com is not accessible in your location
[INFO]       try setting a proxy via HTTP_PROXY, e.g. 
[INFO] 
[INFO]       export HTTP_PROXY=http://example.com:1234
[INFO] 
[INFO] or configure npm proxy via
[INFO] 
[INFO]       npm config set proxy http://example.com:8080
[INFO] 
[INFO] > node-sass@5.0.0 postinstall /data/lect-player-web/src/main/frontend/node_modules/node-sass
[INFO] > node scripts/build.js
[INFO] 
[INFO] Building: /data/lect-player-web/target/node/node /data/lect-player-web/src/main/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
[INFO] gyp info it worked if it ends with ok
[INFO] gyp verb cli [
[INFO] gyp verb cli   '/data/lect-player-web/target/node/node',
[INFO] gyp verb cli   '/data/lect-player-web/src/main/frontend/node_modules/node-gyp/bin/node-gyp.js',
[INFO] gyp verb cli   'rebuild',
[INFO] gyp verb cli   '--verbose',
[INFO] gyp verb cli   '--libsass_ext=',
[INFO] gyp verb cli   '--libsass_cflags=',
[INFO] gyp verb cli   '--libsass_ldflags=',
[INFO] gyp verb cli   '--libsass_library='
[INFO] gyp verb cli ]
[INFO] gyp info using node-gyp@7.1.2
[INFO] gyp info using node@13.14.0 | linux | x64
[INFO] gyp verb command rebuild []
[INFO] gyp verb command clean []
[INFO] gyp verb clean removing "build" directory
[INFO] gyp verb command configure []
[INFO] gyp verb find Python Python is not set from command line or npm configuration
[INFO] gyp verb find Python Python is not set from environment variable PYTHON
[INFO] gyp verb find Python checking if "python3" can be used
[INFO] gyp verb find Python - executing "python3" to get executable path
[INFO] gyp verb find Python - "python3" is not in PATH or produced an error
[INFO] gyp verb find Python checking if "python" can be used
[INFO] gyp verb find Python - executing "python" to get executable path
[INFO] gyp verb find Python - "python" is not in PATH or produced an error
[INFO] gyp verb find Python checking if "python2" can be used
[INFO] gyp verb find Python - executing "python2" to get executable path
[INFO] gyp verb find Python - "python2" is not in PATH or produced an error
[INFO] gyp ERR! find Python 
[INFO] gyp ERR! find Python Python is not set from command line or npm configuration
[INFO] gyp ERR! find Python Python is not set from environment variable PYTHON
[INFO] gyp ERR! find Python checking if "python3" can be used
[INFO] gyp ERR! find Python - "python3" is not in PATH or produced an error
[INFO] gyp ERR! find Python checking if "python" can be used
[INFO] gyp ERR! find Python - "python" is not in PATH or produced an error
[INFO] gyp ERR! find Python checking if "python2" can be used
[INFO] gyp ERR! find Python - "python2" is not in PATH or produced an error
[INFO] gyp ERR! find Python 
[INFO] gyp ERR! find Python **********************************************************
[INFO] gyp ERR! find Python You need to install the latest version of Python.
[INFO] gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
[INFO] gyp ERR! find Python you can try one of the following options:
[INFO] gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
[INFO] gyp ERR! find Python   (accepted by both node-gyp and npm)
[INFO] gyp ERR! find Python - Set the environment variable PYTHON
[INFO] gyp ERR! find Python - Set the npm configuration variable python:
[INFO] gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
[INFO] gyp ERR! find Python For more information consult the documentation at:
[INFO] gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
[INFO] gyp ERR! find Python **********************************************************
[INFO] gyp ERR! find Python 
[INFO] gyp ERR! configure error 
[INFO] gyp ERR! stack Error: Could not find any Python installation to use
[INFO] gyp ERR! stack     at PythonFinder.fail (/data/lect-player-web/src/main/frontend/node_modules/node-gyp/lib/find-python.js:302:47)
[INFO] gyp ERR! stack     at PythonFinder.runChecks (/data/lect-player-web/src/main/frontend/node_modules/node-gyp/lib/find-python.js:136:21)
[INFO] gyp ERR! stack     at PythonFinder.<anonymous> (/data/lect-player-web/src/main/frontend/node_modules/node-gyp/lib/find-python.js:179:16)
[INFO] gyp ERR! stack     at PythonFinder.execFileCallback (/data/lect-player-web/src/main/frontend/node_modules/node-gyp/lib/find-python.js:266:16)
[INFO] gyp ERR! stack     at exithandler (child_process.js:310:5)
[INFO] gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)
[INFO] gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
[INFO] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
[INFO] gyp ERR! stack     at onErrorNT (internal/child_process.js:467:16)
[INFO] gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
[INFO] gyp ERR! System Linux 5.11.0-37-generic
[INFO] gyp ERR! command "/data/lect-player-web/target/node/node" "/data/lect-player-web/src/main/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
[INFO] gyp ERR! cwd /data/lect-player-web/src/main/frontend/node_modules/node-sass
[INFO] gyp ERR! node -v v13.14.0
[INFO] gyp ERR! node-gyp -v v7.1.2
[INFO] gyp ERR! not ok 
[INFO] Build failed with error code: 1
[INFO] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
[INFO] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[INFO] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
[INFO] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[INFO] 
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 1
[INFO] npm ERR! node-sass@5.0.0 postinstall: `node scripts/build.js`
[INFO] npm ERR! Exit status 1
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the node-sass@5.0.0 postinstall script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /root/.npm/_logs/2021-10-06T09_04_39_716Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] lect-studio 4.0.0 .................................. SUCCESS [  3.840 s]
[INFO] lect-thirdparty-parent 1.0.0 ....................... SUCCESS [  0.078 s]
[INFO] concentus 1.0.0 .................................... SUCCESS [  7.980 s]
[INFO] JavaFFmpeg 0.1 ..................................... SUCCESS [  4.762 s]
[INFO] mupdf 1.18.0 ....................................... SUCCESS [  0.214 s]
[INFO] shef 0.5 ........................................... SUCCESS [  1.063 s]
[INFO] lect-core 4.0.0 .................................... SUCCESS [ 12.039 s]
[INFO] lect-swing 4.0.0 ................................... SUCCESS [  2.252 s]
[INFO] lect-web-parent 1.0.0 .............................. SUCCESS [  0.320 s]
[INFO] lect-web-api 1.0.0 ................................. SUCCESS [  6.590 s]
[INFO] lect-media 1.0.0 ................................... SUCCESS [  2.822 s]
[INFO] lect-javafx 1.0.0 .................................. SUCCESS [  7.967 s]
[INFO] lect-web-frontend 1.0.0 ............................ SUCCESS [01:11 min]
[INFO] lect-broadcast 4.0.0 ............................... SUCCESS [ 47.949 s]
[INFO] lect-presenter-api 1.0.0 ........................... SUCCESS [  3.022 s]
[INFO] lect-presenter-fx 4.0.0 ............................ SUCCESS [  6.485 s]
[INFO] lect-presenter-swing 4.0.0 ......................... SUCCESS [  1.337 s]
[INFO] lect-player-api 1.0.0 .............................. SUCCESS [  0.683 s]
[INFO] lect-player-fx 1.0.0 ............................... SUCCESS [  0.762 s]
[INFO] lect-player-web 1.0.0 .............................. FAILURE [ 13.273 s]
[INFO] lect-editor-api 1.0.0 .............................. SKIPPED
[INFO] lect-editor-fx 1.0.0 ............................... SKIPPED
[INFO] lect-packager 4.0.0 ................................ SKIPPED
[INFO] lect-jpackage 1.0.0 ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:25 min
[INFO] Finished at: 2021-10-06T11:04:39+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.2:npm (npm install) on project lect-player-web: Failed to run task: 'npm install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :lect-player-web
```

**Comment by maxkratz** [comment]
Ah, nvm - I had to install some packages (`python3`, `python3-pip`,  `python3-dev`, `build-essential`, `libssl-dev`, and `libffi-dev`) in the container and now maven shows `BUILD SUCCESS`.

I'm going to open a new issue on which packages/programs are needed to build lectureStudio :).
