### ISSUE TITLE
Make http(s) ports of lectureBroadcaster configurable

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#5]
**Is your feature request related to a problem? Please describe.**
As with `lecturePresenter` (#4), I'm unable to start `lectureBroadcaster` (release 4.3.1314 from [official download page](https://www.lecturestudio.org/download)) without super user permissions on my Linux system. (Log output may be found below.)
I found, that this may be related to the fact, that `lectureBroadcaster` binds to the ports 80 and 443 by default, which requires higher permissions on Linux based systems.

```
org.apache.catalina.LifecycleException: Protocol handler initialization failed
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:983)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:533)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:1059)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.startup.Tomcat.init(Tomcat.java:448)
	at org.apache.meecrowave.Meecrowave.start(Meecrowave.java:756)
	at org.apache.meecrowave.Meecrowave.bake(Meecrowave.java:441)
	at org.apache.meecrowave.Meecrowave.bake(Meecrowave.java:437)
	at org.lecturestudio.broadcast.server.MeecrowaveServer.startInternal(MeecrowaveServer.java:127)
	at org.lecturestudio.core.ExecutableBase.start(ExecutableBase.java:100)
	at org.lecturestudio.broadcast.Broadcaster.startInternal(Broadcaster.java:45)
	at org.lecturestudio.core.ExecutableBase.start(ExecutableBase.java:100)
	at org.lecturestudio.broadcast.BroadcasterApplication.startInternal(BroadcasterApplication.java:165)
	at org.lecturestudio.core.app.ApplicationBase.start(ApplicationBase.java:132)
	at org.lecturestudio.core.app.ApplicationBase.launch(ApplicationBase.java:353)
	at org.lecturestudio.core.app.ApplicationBase.launch(ApplicationBase.java:320)
	at org.lecturestudio.core.app.ApplicationBase.launch(ApplicationBase.java:276)
	at org.lecturestudio.broadcast.BroadcasterApplication.main(BroadcasterApplication.java:93)
Caused by: java.net.BindException: Permission denied
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:230)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:213)
	at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1124)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1137)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:574)
	at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:74)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:980)
	... 19 more
```

**Describe the solution you'd like**
A way to configure the default used ports would be very nice. This could for example be implemented by run time arguments:
`$ ./lectureBroadcaster --http_port 10080 --https_port 10443`

**Describe alternatives you've considered**
At least there should be a precise output for the user that explains the problem. This could be something like: "You are running lectureBroadcaster without the permission to bind to port 80 (http) and 443 (https). Consider running the application with root permissions."

**Log output:**
[lectureBroadcaster-output.log](https://github.com/lectureStudio/lectureStudio/files/6177294/lectureBroadcaster-output.log)

**Comment by jomority** [comment]
I can confirm this problem on my machine.

**Comment by devopvoid** [comment]
Hi @maxkratz @jomority,
thanks for the report! It is already possible: `./lectureBroadcaster -p 8080 -tls 8443`, for example.

`./lectureBroadcaster -h` will show you the possible options.

I know, it's not documented. The documentation for the server and streaming stuff is work in progress.

**Comment by jomority** [comment]
I just found out that it is also possible to configure the ports in `.config/lectureBroadcaster/broadcaster.cfg`

**Comment by devopvoid** [comment]
Okay, my bad it should be: `./lectureBroadcaster -help` :blush:

**Comment by maxkratz** [comment]
Thank you both, this resolves the issue!
