### ISSUE TITLE
Linux: Camera does not work

### ISSUE THREAD

**Issue by jomority** [lectureStudio/lectureStudio#8]
**Describe the bug**
When opening the camera settings in lecturePresenter, I get an Exception:
```
V4l2: Capturing rate: 30,00 fps.
V4l2: Capturing format: 1920x1080 MJPG.
Exception in thread "Thread-3" java.lang.RuntimeException: org.lecturestudio.core.camera.CameraException: Pixel format conversion not implemented: [MJPG] -> [RGB3]
	at org.lecturestudio.swing.components.CameraPanel.captureLoop(CameraPanel.java:184)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.lecturestudio.core.camera.CameraException: Pixel format conversion not implemented: [MJPG] -> [RGB3]
	at org.lecturestudio.media.avdev.AVdevCamera.open(AVdevCamera.java:110)
	at org.lecturestudio.swing.components.CameraPanel.captureLoop(CameraPanel.java:170)
	... 1 more
```

**To Reproduce**
1. Download and extract lectureStudio-4.3.1314-linux-x86_64 from the [Download page](https://www.lecturestudio.org/download)
2. Run `./lecturePresenter`
3. Click on "Bearbeiten->Einstellungen"
4. Open the "Camera" tab in the left panel and the Exceptions appears in the console.

**Expected behavior**
I guess the black box on the right (see screenshot below) should be a preview window showing the camera image.

**Screenshots**
![Screenshot from 2021-03-21 18-39-45](https://user-images.githubusercontent.com/7509228/111915079-e2bfeb80-8a74-11eb-8962-e1251578d70d.png)

**Desktop (please complete the following information):**
 - Arch Linux on Gnome

**Additional context**
The Webcam identifies as a `0c45:6366 Microdia Webcam Vitade AF` ([Amazon](https://www.amazon.de/gp/product/B085ZMF2BB/)).

**Comment by maxkratz** [comment]
Can confirm this on Linux Mint 20.1 (Xfce) with a Logitech C920 webcam.

Changing the format to other options did not resolve it:
```
V4l2: Capturing rate: 30,00 fps.
V4l2: Capturing format: 1920x1080 MJPG.
Exception in thread "Thread-4" java.lang.RuntimeException: org.lecturestudio.core.camera.CameraException: Pixel format conversion not implemented: [MJPG] -> [RGB3]
	at org.lecturestudio.swing.components.CameraPanel.captureLoop(CameraPanel.java:184)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.lecturestudio.core.camera.CameraException: Pixel format conversion not implemented: [MJPG] -> [RGB3]
	at org.lecturestudio.media.avdev.AVdevCamera.open(AVdevCamera.java:110)
	at org.lecturestudio.swing.components.CameraPanel.captureLoop(CameraPanel.java:170)
	... 1 more
Exception in thread "Thread-5" java.lang.RuntimeException: org.lecturestudio.core.camera.CameraException: V4l2: Failed setting picture format 1920x1080 RGB3.
	at org.lecturestudio.swing.components.CameraPanel.captureLoop(CameraPanel.java:184)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.lecturestudio.core.camera.CameraException: V4l2: Failed setting picture format 1920x1080 RGB3.
	at org.lecturestudio.media.avdev.AVdevCamera.open(AVdevCamera.java:110)
	at org.lecturestudio.swing.components.CameraPanel.captureLoop(CameraPanel.java:170)
	... 1 more
Exception in thread "Thread-6" java.lang.RuntimeException: org.lecturestudio.core.camera.CameraException: V4l2: Failed setting picture format 1920x1080 RGB3.
	at org.lecturestudio.swing.components.CameraPanel.captureLoop(CameraPanel.java:184)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.lecturestudio.core.camera.CameraException: V4l2: Failed setting picture format 1920x1080 RGB3.
	at org.lecturestudio.media.avdev.AVdevCamera.open(AVdevCamera.java:110)
	at org.lecturestudio.swing.components.CameraPanel.captureLoop(CameraPanel.java:170)
	... 1 more
```

**Comment by jomority** [comment]
I just tested it under Windows with the same camera. There it works.
