### ISSUE TITLE
Presenter (V 6.0.863): Automatischer Wiederaufbau der Verbindung nach Internetproblem

### ISSUE THREAD

**Issue by Andy-Schuerr** [lectureStudio/lectureStudio#820]
Der automatische Wiederaufbau einer Verbindung nach einem Internetproblem (Verbindung zum Server geht verloren) klappt teilweise, es sind aber folgende Fehlfunktionen ab und an beobachtbar:

1) Der Verbindungsaufbau ist erfolgreich, aber nach ein paar Sekunden wird ein erneuter Verbindungsabbruch gemeldet obwohl
    die Internetverbindung stabil ist. Dieser Verbindungsabbruch ist dann endgültig.
2) Beim Wiederaufbau der Verbindung behält irgendein Programmteil des Presenters den Zugriff auf die Webcam, sodass
    die wiederaufgebaute Verbindung keinen Webcam-Zugriff hat. Dann erscheint eine entsprechende Fehlermeldung im
    Presenter und in den Clients fehlt das Kamerafenster ganz. Zudem ist nach Beenden des Streams die Webcam immer
    noch blockiert/eingeschaltet bis der Presenter ganz beendet wird.
3) Manchmal bekommen die Clients einfach gar nicht (oder erst nach langer Zeit) mit, dass der Presenter wieder läuft. 

Testaufbau: die Verbindung zum Server geschieht über WLAN/VPN. Das WLAN wird bei laufendem Stream ausgeschaltet und sobald die Fehlermeldung zum Verbindungsabbruch im Presenter erscheint wieder eingeschaltet.

Ergänzung: wenn die Verbindung des Presenter mit dem Server so schnell wieder aufgebaut wird, dass die Clients den Verbindungsabbruch gar nicht mitbekommen (die Fehlermeldung "Something went wrong" noch nicht anzeigen), dann klappt der Aufbau der Wiederaufbau Verbindung mit dem Client wunderbar (Chrome, Firefox, Brave, ... ). Sobald die Clients aber die Fehlermeldung "Something went wrong" anzeigen bekommen sie danach (meist) nicht mehr mit, wenn die Verbindung von Server zu Presenter wieder steht.

**Comment by Andy-Schuerr** [comment]
Ich habe vergessen das zugehörige Log mit hochzuladen, vielleicht hilft es ja:

2023-09-29 10:51:33,792 ERROR ExecutableBase:256 - Janus websocket error
java.net.SocketException: Connection reset
	at sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:?]
	at jdk.internal.net.http.SocketTube.readAvailable(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$SocketFlowTask.run(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(Unknown Source) ~[java.net.http:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source) ~[java.net.http:?]
2023-09-29 10:52:12,693 ERROR ExecutableBase:249 - Janus error: No such session 5836613098885352 (error code: 458)
2023-09-29 10:52:12,695 ERROR ExecutableBase:249 - Janus error: No such session 5836613098885352 (error code: 458)
2023-09-29 10:52:13,204 ERROR ExecutableBase:249 - Janus error: No such session 8291869062433839 (error code: 458)
2023-09-29 10:52:13,391 ERROR ExecutableBase:256 - Janus state error
org.lecturestudio.web.api.janus.JanusHandlerException: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusHandler$1.error(JanusHandler.java:381) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusStateHandler.setError(JanusStateHandler.java:185) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$notify$9(JanusPeerConnection.java:692) ~[lect-web-api.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:362) ~[lect-web-api.jar:?]
	... 3 more
Caused by: java.lang.Error: Unhandled Exception
	at dev.onvoid.webrtc.media.video.VideoDeviceSource.start(Native Method) ~[webrtc-java.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:359) ~[lect-web-api.jar:?]
	... 3 more
2023-09-29 10:54:42,032 ERROR WebSocketClientHandler:64 - WebSocket error: Connection reset
2023-09-29 11:15:14,172 ERROR WebSocketClientHandler:64 - WebSocket error: Connection reset

**Comment by Andy-Schuerr** [comment]
Heute konnte ich die Kameraprobleme bei Verbindungsabbrüchen des Presenters unbeabsichtigt erneut beobachten:
- Beim Testen ist die Internetverbindung tatsächlich zusammengebrochen und der Presenter hat die Verbindung zum Server verloren.
- Die Wiederherstellung der Verbindung hat nicht geklappt, da u.a. die Kamera als von einem anderen Programm genutzt gemeldet wurde.

Hier ist die Log-Datei dazu:
2023-10-07 11:18:04,464 ERROR WebSocketClientHandler:64 - WebSocket error: Connection reset
2023-10-07 11:18:04,465 ERROR ExecutableBase:256 - Janus websocket error
java.net.SocketException: Connection reset
	at sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:?]
	at jdk.internal.net.http.SocketTube.readAvailable(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$SocketFlowTask.run(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(Unknown Source) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(Unknown Source) ~[java.net.http:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source) ~[java.net.http:?]
2023-10-07 11:18:27,457 ERROR ExecutableBase:249 - Janus error: No such session 6432956271673517 (error code: 458)
2023-10-07 11:18:27,459 ERROR ExecutableBase:249 - Janus error: No such session 6432956271673517 (error code: 458)
2023-10-07 11:18:27,979 ERROR ExecutableBase:249 - Janus error: No such session 6177143481171200 (error code: 458)
2023-10-07 11:18:27,981 ERROR ExecutableBase:249 - Janus error: No such session 6177143481171200 (error code: 458)
2023-10-07 11:18:28,165 ERROR ExecutableBase:256 - Janus state error
org.lecturestudio.web.api.janus.JanusHandlerException: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusHandler$1.error(JanusHandler.java:381) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusStateHandler.setError(JanusStateHandler.java:185) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$notify$9(JanusPeerConnection.java:692) ~[lect-web-api.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:362) ~[lect-web-api.jar:?]
	... 3 more
Caused by: java.lang.Error: Unhandled Exception
	at dev.onvoid.webrtc.media.video.VideoDeviceSource.start(Native Method) ~[webrtc-java.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:359) ~[lect-web-api.jar:?]
	... 3 more
2023-10-07 11:18:28,495 ERROR ExecutableBase:249 - Janus error: No such session 33750068128829 (error code: 458)
2023-10-07 11:18:28,497 ERROR ExecutableBase:249 - Janus error: No such session 33750068128829 (error code: 458)
2023-10-07 11:18:28,673 ERROR ExecutableBase:256 - Janus state error
org.lecturestudio.web.api.janus.JanusHandlerException: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusHandler$1.error(JanusHandler.java:381) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusStateHandler.setError(JanusStateHandler.java:185) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$notify$9(JanusPeerConnection.java:692) ~[lect-web-api.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:362) ~[lect-web-api.jar:?]
	... 3 more
Caused by: java.lang.Error: Unhandled Exception
	at dev.onvoid.webrtc.media.video.VideoDeviceSource.start(Native Method) ~[webrtc-java.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:359) ~[lect-web-api.jar:?]
	... 3 more
2023-10-07 11:18:55,478 ERROR ExecutableBase:249 - Janus error: No such room (error code: 426)
2023-10-07 11:18:55,591 ERROR ExecutableBase:256 - Janus state error
org.lecturestudio.web.api.janus.JanusHandlerException: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusHandler$1.error(JanusHandler.java:381) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusStateHandler.setError(JanusStateHandler.java:185) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$notify$9(JanusPeerConnection.java:692) ~[lect-web-api.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:362) ~[lect-web-api.jar:?]
	... 3 more
Caused by: java.lang.Error: Unhandled Exception
	at dev.onvoid.webrtc.media.video.VideoDeviceSource.start(Native Method) ~[webrtc-java.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:359) ~[lect-web-api.jar:?]
	... 3 more
2023-10-07 11:18:56,021 ERROR ExecutableBase:256 - Janus state error
org.lecturestudio.web.api.janus.JanusHandlerException: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusHandler$1.error(JanusHandler.java:381) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusStateHandler.setError(JanusStateHandler.java:185) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$notify$9(JanusPeerConnection.java:692) ~[lect-web-api.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:362) ~[lect-web-api.jar:?]
	... 3 more
Caused by: java.lang.Error: Unhandled Exception
	at dev.onvoid.webrtc.media.video.VideoDeviceSource.start(Native Method) ~[webrtc-java.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:359) ~[lect-web-api.jar:?]
	... 3 more
2023-10-07 11:19:23,703 ERROR ExecutableBase:256 - Janus state error
org.lecturestudio.web.api.janus.JanusHandlerException: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusHandler$1.error(JanusHandler.java:381) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusStateHandler.setError(JanusStateHandler.java:185) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$notify$9(JanusPeerConnection.java:692) ~[lect-web-api.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:362) ~[lect-web-api.jar:?]
	... 3 more
Caused by: java.lang.Error: Unhandled Exception
	at dev.onvoid.webrtc.media.video.VideoDeviceSource.start(Native Method) ~[webrtc-java.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:359) ~[lect-web-api.jar:?]
	... 3 more
2023-10-07 11:19:24,201 ERROR ExecutableBase:256 - Janus state error
org.lecturestudio.web.api.janus.JanusHandlerException: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusHandler$1.error(JanusHandler.java:381) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusStateHandler.setError(JanusStateHandler.java:185) ~[lect-web-api.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$notify$9(JanusPeerConnection.java:692) ~[lect-web-api.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.lecturestudio.web.api.janus.JanusPeerConnectionMediaException: Start video capture source failed
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:362) ~[lect-web-api.jar:?]
	... 3 more
Caused by: java.lang.Error: Unhandled Exception
	at dev.onvoid.webrtc.media.video.VideoDeviceSource.start(Native Method) ~[webrtc-java.jar:?]
	at org.lecturestudio.web.api.janus.JanusPeerConnection.lambda$setCameraEnabled$7(JanusPeerConnection.java:359) ~[lect-web-api.jar:?]
	... 3 more

**Comment by Andy-Schuerr** [comment]
Das Verhalten des Presenters bei Internetverbindungsabbrüchen hat sich leider nicht verbessert. Folgendes Experiment scheitert immer noch:

1) Presenter läuft auf einem über LAN angebundenen Rechner mit VPN-Verbindung.
2) Client läuft auf einem weiteren Rechner.

LAN-Verbindung wird unterbrochen, ca. 10 Sekunden gewartet und dann wieder hergestellt. Dann behauptet der Presenter nachdem die VPN-Verbindung wieder steht kurz, dass die Verbindung zum Server wieder steht und der Stream wieder hergestellt wurde. In der Tat kann sich der Client danach automatisch wieder mit dem Server/Stream verbinden, aber nur im Hörsaalmodus. Die Übersichtsseite zeigt auch "nur" an, dass der Chat läuft, der Stream selbst nicht.

Der Presenter zeigt inzwischen im 10-Sekundentakt Verbindungsabbrüche an (obwohl die Internetverbindung wieder stabil ist) und verbindet sich wieder (aber nur Chat), zeigt dann wieder einen Verbindungsabbruch an und verbindet sich wieder und ... .
