### ISSUE TITLE
lectureEditor (v6.1.1025): Crashes when opening my recording

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#985]
**Describe the bug**

**To Reproduce**
1. Open `lectureEditor`
2. Load the recording of my presentation yesterday
3. The slide display freezes and playback is not possible

(Works fine on Windows, though!)

**Expected behavior**
No exception, playback, and slide actions

**Desktop (please complete the following information):**
 - OS: Linux, Pop!_OS 22.04 LTS x86_64, kernel 6.9.3-76060903-generic, desktop environment GNOME 42.9

**Additional context**
Console output:
```
$ ./lectureEditor
2024-12-12 10:00:01,496 WARN  javafx:-1 - Unsupported JavaFX configuration: classes were loaded from unnamed module @192c3f1e

(lectureEditor:51742): Gdk-WARNING **: 10:00:03.939: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
Error getting static method ID of org/bytedeco/javacpp/Loader/putMemberOffset
2024-12-12 10:00:07,477 ERROR RecordingPlaybackService:126 - Initialize recording failed
org.lecturestudio.core.ExecutableException: Failed to initialize Executable component [org.lecturestudio.editor.api.service.RecordingPlaybackService@712f879f]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:81) ~[lect-core.jar:?]
	at org.lecturestudio.editor.api.service.RecordingPlaybackService.setRecording(RecordingPlaybackService.java:123) ~[lect-editor-api.jar:?]
	at org.lecturestudio.editor.api.service.RecordingFileService.selectRecording(RecordingFileService.java:198) ~[lect-editor-api.jar:?]
	at org.lecturestudio.editor.api.service.RecordingFileService.lambda$openRecording$0(RecordingFileService.java:120) ~[lect-editor-api.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: org.lecturestudio.core.ExecutableException: Failed to initialize Executable component [org.lecturestudio.media.playback.RecordingPlayer@43bc531a]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:81) ~[lect-core.jar:?]
	at org.lecturestudio.editor.api.service.RecordingPlaybackService.initInternal(RecordingPlaybackService.java:213) ~[lect-editor-api.jar:?]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:76) ~[lect-core.jar:?]
	... 10 more
Caused by: org.lecturestudio.core.ExecutableException: Failed to initialize Executable component [org.lecturestudio.media.playback.FileEventExecutor@4d4825c4]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:81) ~[lect-core.jar:?]
	at org.lecturestudio.media.playback.RecordingPlayer.initInternal(RecordingPlayer.java:149) ~[lect-media.jar:?]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:76) ~[lect-core.jar:?]
	at org.lecturestudio.editor.api.service.RecordingPlaybackService.initInternal(RecordingPlaybackService.java:213) ~[lect-editor-api.jar:?]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:76) ~[lect-core.jar:?]
	... 10 more
Caused by: org.lecturestudio.core.ExecutableException: org.lecturestudio.media.video.FFmpegFrameGrabber$Exception: Failed to load class org.lecturestudio.media.video.FFmpegFrameGrabber
	at org.lecturestudio.media.playback.FileEventExecutor.initInternal(FileEventExecutor.java:129) ~[lect-media.jar:?]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:76) ~[lect-core.jar:?]
	at org.lecturestudio.media.playback.RecordingPlayer.initInternal(RecordingPlayer.java:149) ~[lect-media.jar:?]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:76) ~[lect-core.jar:?]
	at org.lecturestudio.editor.api.service.RecordingPlaybackService.initInternal(RecordingPlaybackService.java:213) ~[lect-editor-api.jar:?]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:76) ~[lect-core.jar:?]
	... 10 more
Caused by: org.lecturestudio.media.video.FFmpegFrameGrabber$Exception: Failed to load class org.lecturestudio.media.video.FFmpegFrameGrabber
	at org.lecturestudio.media.video.FFmpegFrameGrabber.tryLoad(FFmpegFrameGrabber.java:132) ~[lect-media.jar:?]
	at org.lecturestudio.media.video.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:140) ~[lect-media.jar:?]
	at org.lecturestudio.media.playback.FileEventExecutor.initInternal(FileEventExecutor.java:126) ~[lect-media.jar:?]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:76) ~[lect-core.jar:?]
	at org.lecturestudio.media.playback.RecordingPlayer.initInternal(RecordingPlayer.java:149) ~[lect-media.jar:?]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:76) ~[lect-core.jar:?]
	at org.lecturestudio.editor.api.service.RecordingPlaybackService.initInternal(RecordingPlaybackService.java:213) ~[lect-editor-api.jar:?]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:76) ~[lect-core.jar:?]
	... 10 more
Caused by: java.lang.NoSuchMethodError: static Lorg/bytedeco/javacpp/Loader;.putMemberOffset(Ljava/lang/String;Ljava/lang/String;I)V
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source) ~[?:?]
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source) ~[?:?]
	at java.base/java.lang.System.loadLibrary(Unknown Source) ~[?:?]
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832) ~[javacpp.jar:1.5.10]
	at org.bytedeco.javacpp.Loader.load(Loader.java:1423) ~[javacpp.jar:1.5.10]
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234) ~[javacpp.jar:1.5.10]
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210) ~[javacpp.jar:1.5.10]
	at org.bytedeco.ffmpeg.global.postproc.<clinit>(postproc.java:16) ~[ffmpeg.jar:6.1.1-1.5.10]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Unknown Source) ~[?:?]
	at org.bytedeco.javacpp.Loader.load(Loader.java:1289) ~[javacpp.jar:1.5.10]
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234) ~[javacpp.jar:1.5.10]
	at org.bytedeco.javacpp.Loader.load(Loader.java:1226) ~[javacpp.jar:1.5.10]
	at org.lecturestudio.media.video.FFmpegFrameGrabber.tryLoad(FFmpegFrameGrabber.java:126) ~[lect-media.jar:?]
	at org.lecturestudio.media.video.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:140) ~[lect-media.jar:?]
	at org.lecturestudio.media.playback.FileEventExecutor.initInternal(FileEventExecutor.java:126) ~[lect-media.jar:?]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:76) ~[lect-core.jar:?]
	at org.lecturestudio.media.playback.RecordingPlayer.initInternal(RecordingPlayer.java:149) ~[lect-media.jar:?]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:76) ~[lect-core.jar:?]
	at org.lecturestudio.editor.api.service.RecordingPlaybackService.initInternal(RecordingPlaybackService.java:213) ~[lect-editor-api.jar:?]
	at org.lecturestudio.core.ExecutableBase.init(ExecutableBase.java:76) ~[lect-core.jar:?]
	... 10 more

```

**Comment by devopvoid** [comment]
Der Fehler tritt in Zusammenhang mit einer Aufzeichnung eines Screen-Shares auf.
